name: Graduation Dispatch

on:
  repository_dispatch:
    types: [graduation_triggered]

jobs:
  update-token-info:
    name: Update Token Metadata and Notify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout token-info repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          pip install requests

      - name: Update metadata
        run: |
          jq '(.tokens[] | select(.address == "51ey1T4UCFwb8poVBwyiLwwi1KdNTrZ8rSg7kBRmqray") 
              | .tags) += ["graduated", "featured"]' token-list.json > tmp.json
          mv tmp.json token-list.json

      - name: Commit and push
        run: |
          git config --global user.name "BoomchainLabs CI Bot"
          git config --global user.email "support@boomchainlab.com"
          git add token-list.json
          git commit -m "chore: CHONKPUMP 9000 graduated 🎓"
          git push origin main

      - name: Notify Twitter
        if: env.TWITTER_WEBHOOK != ''
        env:
          TWITTER_WEBHOOK: ${{ secrets.TWITTER_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d \
          '{"message": "🎓 CHONKPUMP 9000 has officially graduated. Beast Mode activated. #CHONK9000"}' \
          "$TWITTER_WEBHOOK"

      - name: Notify Raydium
        if: env.RAYDIUM_DISCORD != ''
        env:
          RAYDIUM_DISCORD: ${{ secrets.RAYDIUM_DISCORD }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d \
          '{"content": "**$CHONKPUMP 9000 has graduated!** Raydium LP: https://raydium.io/swap/?inputCurrency=sol&outputCurrency=51ey1T4UCFwb8poVBwyiLwwi1KdNTrZ8rSg7kBRmqray"}' \
          "$RAYDIUM_DISCORD"
